// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ubaniak/scoreboard/internal/athletes (interfaces: UseCase)
//
// Generated by this command:
//
//	mockgen -destination=./internal/roster/mocks/mock_athletes_usecase.go -package=mocks github.com/ubaniak/scoreboard/internal/athletes UseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "github.com/ubaniak/scoreboard/internal/athletes/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
	isgomock struct{}
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUseCase) Create(name, ageCategory, gender, experience string, clubAffiliationID, provinceAffiliationID, nationAffiliationID *uint, weightClass *float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name, ageCategory, gender, experience, clubAffiliationID, provinceAffiliationID, nationAffiliationID, weightClass)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUseCaseMockRecorder) Create(name, ageCategory, gender, experience, clubAffiliationID, provinceAffiliationID, nationAffiliationID, weightClass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUseCase)(nil).Create), name, ageCategory, gender, experience, clubAffiliationID, provinceAffiliationID, nationAffiliationID, weightClass)
}

// Delete mocks base method.
func (m *MockUseCase) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUseCaseMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUseCase)(nil).Delete), id)
}

// FindOrCreateByName mocks base method.
func (m *MockUseCase) FindOrCreateByName(name, clubName string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreateByName", name, clubName)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreateByName indicates an expected call of FindOrCreateByName.
func (mr *MockUseCaseMockRecorder) FindOrCreateByName(name, clubName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreateByName", reflect.TypeOf((*MockUseCase)(nil).FindOrCreateByName), name, clubName)
}

// FindOrCreateByNameAndClub mocks base method.
func (m *MockUseCase) FindOrCreateByNameAndClub(name string, clubAffiliationID *uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreateByNameAndClub", name, clubAffiliationID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreateByNameAndClub indicates an expected call of FindOrCreateByNameAndClub.
func (mr *MockUseCaseMockRecorder) FindOrCreateByNameAndClub(name, clubAffiliationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreateByNameAndClub", reflect.TypeOf((*MockUseCase)(nil).FindOrCreateByNameAndClub), name, clubAffiliationID)
}

// FindOrCreateByNameClubProvince mocks base method.
func (m *MockUseCase) FindOrCreateByNameClubProvince(name string, clubAffiliationID, provinceAffiliationID *uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreateByNameClubProvince", name, clubAffiliationID, provinceAffiliationID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreateByNameClubProvince indicates an expected call of FindOrCreateByNameClubProvince.
func (mr *MockUseCaseMockRecorder) FindOrCreateByNameClubProvince(name, clubAffiliationID, provinceAffiliationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreateByNameClubProvince", reflect.TypeOf((*MockUseCase)(nil).FindOrCreateByNameClubProvince), name, clubAffiliationID, provinceAffiliationID)
}

// FindOrCreateFull mocks base method.
func (m *MockUseCase) FindOrCreateFull(name, ageCategory, gender, experience string, clubAffiliationID, provinceAffiliationID, nationAffiliationID *uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreateFull", name, ageCategory, gender, experience, clubAffiliationID, provinceAffiliationID, nationAffiliationID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreateFull indicates an expected call of FindOrCreateFull.
func (mr *MockUseCaseMockRecorder) FindOrCreateFull(name, ageCategory, gender, experience, clubAffiliationID, provinceAffiliationID, nationAffiliationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreateFull", reflect.TypeOf((*MockUseCase)(nil).FindOrCreateFull), name, ageCategory, gender, experience, clubAffiliationID, provinceAffiliationID, nationAffiliationID)
}

// Get mocks base method.
func (m *MockUseCase) Get(id uint) (*entities.Athlete, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*entities.Athlete)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUseCaseMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUseCase)(nil).Get), id)
}

// List mocks base method.
func (m *MockUseCase) List() ([]entities.Athlete, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]entities.Athlete)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUseCaseMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUseCase)(nil).List))
}

// SetImageUrl mocks base method.
func (m *MockUseCase) SetImageUrl(id uint, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetImageUrl", id, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetImageUrl indicates an expected call of SetImageUrl.
func (mr *MockUseCaseMockRecorder) SetImageUrl(id, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetImageUrl", reflect.TypeOf((*MockUseCase)(nil).SetImageUrl), id, url)
}

// Update mocks base method.
func (m *MockUseCase) Update(id uint, toUpdate *entities.UpdateAthlete) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, toUpdate)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUseCaseMockRecorder) Update(id, toUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUseCase)(nil).Update), id, toUpdate)
}
