// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ubaniak/scoreboard/internal/roster (interfaces: Storage)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_storage.go -package=mocks github.com/ubaniak/scoreboard/internal/roster Storage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "github.com/ubaniak/scoreboard/internal/creation/roster/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockStorage) Add(cardID, athleteID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", cardID, athleteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockStorageMockRecorder) Add(cardID, athleteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockStorage)(nil).Add), cardID, athleteID)
}

// Get mocks base method.
func (m *MockStorage) Get(cardID, athleteID uint) (*entities.RosterEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", cardID, athleteID)
	ret0, _ := ret[0].(*entities.RosterEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStorageMockRecorder) Get(cardID, athleteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorage)(nil).Get), cardID, athleteID)
}

// ListForCard mocks base method.
func (m *MockStorage) ListForCard(cardID uint) ([]entities.RosterEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForCard", cardID)
	ret0, _ := ret[0].([]entities.RosterEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForCard indicates an expected call of ListForCard.
func (mr *MockStorageMockRecorder) ListForCard(cardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForCard", reflect.TypeOf((*MockStorage)(nil).ListForCard), cardID)
}

// Remove mocks base method.
func (m *MockStorage) Remove(cardID, athleteID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", cardID, athleteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockStorageMockRecorder) Remove(cardID, athleteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockStorage)(nil).Remove), cardID, athleteID)
}

// SetAvailable mocks base method.
func (m *MockStorage) SetAvailable(cardID, athleteID uint, available bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAvailable", cardID, athleteID, available)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAvailable indicates an expected call of SetAvailable.
func (mr *MockStorageMockRecorder) SetAvailable(cardID, athleteID, available any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAvailable", reflect.TypeOf((*MockStorage)(nil).SetAvailable), cardID, athleteID, available)
}
