// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ubaniak/scoreboard/internal/roster (interfaces: BoutAthleteQuerier)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_bout_querier.go -package=mocks github.com/ubaniak/scoreboard/internal/roster BoutAthleteQuerier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBoutAthleteQuerier is a mock of BoutAthleteQuerier interface.
type MockBoutAthleteQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockBoutAthleteQuerierMockRecorder
	isgomock struct{}
}

// MockBoutAthleteQuerierMockRecorder is the mock recorder for MockBoutAthleteQuerier.
type MockBoutAthleteQuerierMockRecorder struct {
	mock *MockBoutAthleteQuerier
}

// NewMockBoutAthleteQuerier creates a new mock instance.
func NewMockBoutAthleteQuerier(ctrl *gomock.Controller) *MockBoutAthleteQuerier {
	mock := &MockBoutAthleteQuerier{ctrl: ctrl}
	mock.recorder = &MockBoutAthleteQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoutAthleteQuerier) EXPECT() *MockBoutAthleteQuerierMockRecorder {
	return m.recorder
}

// IsAthleteMatched mocks base method.
func (m *MockBoutAthleteQuerier) IsAthleteMatched(cardID, athleteID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAthleteMatched", cardID, athleteID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAthleteMatched indicates an expected call of IsAthleteMatched.
func (mr *MockBoutAthleteQuerierMockRecorder) IsAthleteMatched(cardID, athleteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAthleteMatched", reflect.TypeOf((*MockBoutAthleteQuerier)(nil).IsAthleteMatched), cardID, athleteID)
}
