// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ubaniak/scoreboard/internal/running/boutrunner (interfaces: Storage)
//
// Generated by this command:
//
//	mockgen -destination=./internal/running/boutrunner/mocks/mock_storage.go -package=mocks github.com/ubaniak/scoreboard/internal/running/boutrunner Storage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "github.com/ubaniak/scoreboard/internal/matchmaking/bouts/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Current mocks base method.
func (m *MockStorage) Current(cardId uint) (*entities.Bout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current", cardId)
	ret0, _ := ret[0].(*entities.Bout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Current indicates an expected call of Current.
func (mr *MockStorageMockRecorder) Current(cardId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockStorage)(nil).Current), cardId)
}

// Get mocks base method.
func (m *MockStorage) Get(cardId, id uint) (*entities.Bout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", cardId, id)
	ret0, _ := ret[0].(*entities.Bout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStorageMockRecorder) Get(cardId, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorage)(nil).Get), cardId, id)
}

// SetStatus mocks base method.
func (m *MockStorage) SetStatus(cardId, id uint, status entities.BoutStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", cardId, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockStorageMockRecorder) SetStatus(cardId, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockStorage)(nil).SetStatus), cardId, id, status)
}

// Update mocks base method.
func (m *MockStorage) Update(cardId, id uint, bout *entities.UpdateBout) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", cardId, id, bout)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStorageMockRecorder) Update(cardId, id, bout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStorage)(nil).Update), cardId, id, bout)
}
