// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ubaniak/scoreboard/internal/matchmaking/bouts (interfaces: RosterAvailability)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_roster_availability.go -package=mocks github.com/ubaniak/scoreboard/internal/matchmaking/bouts RosterAvailability
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRosterAvailability is a mock of RosterAvailability interface.
type MockRosterAvailability struct {
	ctrl     *gomock.Controller
	recorder *MockRosterAvailabilityMockRecorder
	isgomock struct{}
}

// MockRosterAvailabilityMockRecorder is the mock recorder for MockRosterAvailability.
type MockRosterAvailabilityMockRecorder struct {
	mock *MockRosterAvailability
}

// NewMockRosterAvailability creates a new mock instance.
func NewMockRosterAvailability(ctrl *gomock.Controller) *MockRosterAvailability {
	mock := &MockRosterAvailability{ctrl: ctrl}
	mock.recorder = &MockRosterAvailabilityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRosterAvailability) EXPECT() *MockRosterAvailabilityMockRecorder {
	return m.recorder
}

// SetAvailable mocks base method.
func (m *MockRosterAvailability) SetAvailable(cardID, athleteID uint, available bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAvailable", cardID, athleteID, available)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAvailable indicates an expected call of SetAvailable.
func (mr *MockRosterAvailabilityMockRecorder) SetAvailable(cardID, athleteID, available any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAvailable", reflect.TypeOf((*MockRosterAvailability)(nil).SetAvailable), cardID, athleteID, available)
}
