// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ubaniak/scoreboard/internal/comment (interfaces: UseCase)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_comment_usecase.go -package=mocks github.com/ubaniak/scoreboard/internal/comment UseCase
//

package mocks

import (
	reflect "reflect"

	entities "github.com/ubaniak/scoreboard/internal/comment/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockCommentUseCase is a mock of comment.UseCase interface.
type MockCommentUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCommentUseCaseMockRecorder
	isgomock struct{}
}

// MockCommentUseCaseMockRecorder is the mock recorder for MockCommentUseCase.
type MockCommentUseCaseMockRecorder struct {
	mock *MockCommentUseCase
}

// NewMockCommentUseCase creates a new mock instance.
func NewMockCommentUseCase(ctrl *gomock.Controller) *MockCommentUseCase {
	mock := &MockCommentUseCase{ctrl: ctrl}
	mock.recorder = &MockCommentUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentUseCase) EXPECT() *MockCommentUseCaseMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockCommentUseCase) Add(entityKind string, entityId uint, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", entityKind, entityId, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockCommentUseCaseMockRecorder) Add(entityKind, entityId, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCommentUseCase)(nil).Add), entityKind, entityId, comment)
}

// Get mocks base method.
func (m *MockCommentUseCase) Get(entityKind string, entityId uint) ([]entities.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", entityKind, entityId)
	ret0, _ := ret[0].([]entities.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCommentUseCaseMockRecorder) Get(entityKind, entityId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCommentUseCase)(nil).Get), entityKind, entityId)
}
