// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ubaniak/scoreboard/internal/scores (interfaces: UseCase)
//
// Generated by this command:
//
//	mockgen -destination=./internal/bouts/mocks/mock_scores_usecase.go -package=mocks -mock_names UseCase=MockScoresUseCase github.com/ubaniak/scoreboard/internal/scores UseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "github.com/ubaniak/scoreboard/internal/scores/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockScoresUseCase is a mock of UseCase interface.
type MockScoresUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockScoresUseCaseMockRecorder
	isgomock struct{}
}

// MockScoresUseCaseMockRecorder is the mock recorder for MockScoresUseCase.
type MockScoresUseCaseMockRecorder struct {
	mock *MockScoresUseCase
}

// NewMockScoresUseCase creates a new mock instance.
func NewMockScoresUseCase(ctrl *gomock.Controller) *MockScoresUseCase {
	mock := &MockScoresUseCase{ctrl: ctrl}
	mock.recorder = &MockScoresUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScoresUseCase) EXPECT() *MockScoresUseCaseMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockScoresUseCase) Complete(cardId, boutId uint, roundNumber int, JudgeRole string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", cardId, boutId, roundNumber, JudgeRole)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockScoresUseCaseMockRecorder) Complete(cardId, boutId, roundNumber, JudgeRole any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockScoresUseCase)(nil).Complete), cardId, boutId, roundNumber, JudgeRole)
}

// Create mocks base method.
func (m *MockScoresUseCase) Create(cardId, boutId uint, numberOfJudges int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", cardId, boutId, numberOfJudges)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockScoresUseCaseMockRecorder) Create(cardId, boutId, numberOfJudges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScoresUseCase)(nil).Create), cardId, boutId, numberOfJudges)
}

// List mocks base method.
func (m *MockScoresUseCase) List(cardId, boutId uint) ([]*entities.Score, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cardId, boutId)
	ret0, _ := ret[0].([]*entities.Score)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockScoresUseCaseMockRecorder) List(cardId, boutId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockScoresUseCase)(nil).List), cardId, boutId)
}

// Ready mocks base method.
func (m *MockScoresUseCase) Ready(cardId, boutId uint, roundNumber int, judgeRole, judgeName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ready", cardId, boutId, roundNumber, judgeRole, judgeName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ready indicates an expected call of Ready.
func (mr *MockScoresUseCaseMockRecorder) Ready(cardId, boutId, roundNumber, judgeRole, judgeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ready", reflect.TypeOf((*MockScoresUseCase)(nil).Ready), cardId, boutId, roundNumber, judgeRole, judgeName)
}

// Recreate mocks base method.
func (m *MockScoresUseCase) Recreate(cardId, boutId uint, numberOfJudges int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recreate", cardId, boutId, numberOfJudges)
	ret0, _ := ret[0].(error)
	return ret0
}

// Recreate indicates an expected call of Recreate.
func (mr *MockScoresUseCaseMockRecorder) Recreate(cardId, boutId, numberOfJudges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recreate", reflect.TypeOf((*MockScoresUseCase)(nil).Recreate), cardId, boutId, numberOfJudges)
}

// RequestScores mocks base method.
func (m *MockScoresUseCase) RequestScores(cardId, boutId uint, roundNumber int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestScores", cardId, boutId, roundNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestScores indicates an expected call of RequestScores.
func (mr *MockScoresUseCaseMockRecorder) RequestScores(cardId, boutId, roundNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestScores", reflect.TypeOf((*MockScoresUseCase)(nil).RequestScores), cardId, boutId, roundNumber)
}

// Score mocks base method.
func (m *MockScoresUseCase) Score(cardId, boutId uint, roundNumber int, JudgeRole string, red, blue int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Score", cardId, boutId, roundNumber, JudgeRole, red, blue)
	ret0, _ := ret[0].(error)
	return ret0
}

// Score indicates an expected call of Score.
func (mr *MockScoresUseCaseMockRecorder) Score(cardId, boutId, roundNumber, JudgeRole, red, blue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Score", reflect.TypeOf((*MockScoresUseCase)(nil).Score), cardId, boutId, roundNumber, JudgeRole, red, blue)
}
