// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ubaniak/scoreboard/internal/round (interfaces: UseCase)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_round_usecase.go -package=mocks github.com/ubaniak/scoreboard/internal/round UseCase
//

package mocks

import (
	reflect "reflect"

	entities "github.com/ubaniak/scoreboard/internal/round/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockRoundUseCase is a mock of round.UseCase interface.
type MockRoundUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRoundUseCaseMockRecorder
	isgomock struct{}
}

// MockRoundUseCaseMockRecorder is the mock recorder for MockRoundUseCase.
type MockRoundUseCaseMockRecorder struct {
	mock *MockRoundUseCase
}

// NewMockRoundUseCase creates a new mock instance.
func NewMockRoundUseCase(ctrl *gomock.Controller) *MockRoundUseCase {
	mock := &MockRoundUseCase{ctrl: ctrl}
	mock.recorder = &MockRoundUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoundUseCase) EXPECT() *MockRoundUseCaseMockRecorder {
	return m.recorder
}

// AddFoul mocks base method.
func (m *MockRoundUseCase) AddFoul(roundFoul *entities.RoundFoul) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFoul", roundFoul)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFoul indicates an expected call of AddFoul.
func (mr *MockRoundUseCaseMockRecorder) AddFoul(roundFoul any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFoul", reflect.TypeOf((*MockRoundUseCase)(nil).AddFoul), roundFoul)
}

// CreateRounds mocks base method.
func (m *MockRoundUseCase) CreateRounds(boutID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRounds", boutID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRounds indicates an expected call of CreateRounds.
func (mr *MockRoundUseCaseMockRecorder) CreateRounds(boutID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRounds", reflect.TypeOf((*MockRoundUseCase)(nil).CreateRounds), boutID)
}

// Current mocks base method.
func (m *MockRoundUseCase) Current(boutId uint) (*entities.Round, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current", boutId)
	ret0, _ := ret[0].(*entities.Round)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Current indicates an expected call of Current.
func (mr *MockRoundUseCaseMockRecorder) Current(boutId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockRoundUseCase)(nil).Current), boutId)
}

// EightCount mocks base method.
func (m *MockRoundUseCase) EightCount(boutId uint, roundNumber int, corner string, direction string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EightCount", boutId, roundNumber, corner, direction)
	ret0, _ := ret[0].(error)
	return ret0
}

// EightCount indicates an expected call of EightCount.
func (mr *MockRoundUseCaseMockRecorder) EightCount(boutId, roundNumber, corner, direction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EightCount", reflect.TypeOf((*MockRoundUseCase)(nil).EightCount), boutId, roundNumber, corner, direction)
}

// Get mocks base method.
func (m *MockRoundUseCase) Get(boutId uint, roundNumber int) (*entities.RoundDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", boutId, roundNumber)
	ret0, _ := ret[0].(*entities.RoundDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRoundUseCaseMockRecorder) Get(boutId, roundNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRoundUseCase)(nil).Get), boutId, roundNumber)
}

// List mocks base method.
func (m *MockRoundUseCase) List(boutId uint) ([]*entities.Round, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", boutId)
	ret0, _ := ret[0].([]*entities.Round)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRoundUseCaseMockRecorder) List(boutId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRoundUseCase)(nil).List), boutId)
}

// ListFouls mocks base method.
func (m *MockRoundUseCase) ListFouls() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFouls")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFouls indicates an expected call of ListFouls.
func (mr *MockRoundUseCaseMockRecorder) ListFouls() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFouls", reflect.TypeOf((*MockRoundUseCase)(nil).ListFouls))
}

// Next mocks base method.
func (m *MockRoundUseCase) Next(boutId uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next", boutId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Next indicates an expected call of Next.
func (mr *MockRoundUseCaseMockRecorder) Next(boutId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockRoundUseCase)(nil).Next), boutId)
}

// RemoveFoul mocks base method.
func (m *MockRoundUseCase) RemoveFoul(roundFoul *entities.RoundFoul) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFoul", roundFoul)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFoul indicates an expected call of RemoveFoul.
func (mr *MockRoundUseCaseMockRecorder) RemoveFoul(roundFoul any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFoul", reflect.TypeOf((*MockRoundUseCase)(nil).RemoveFoul), roundFoul)
}

// UpdateStatus mocks base method.
func (m *MockRoundUseCase) UpdateStatus(boutId uint, roundNumber int, status entities.RoundStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", boutId, roundNumber, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRoundUseCaseMockRecorder) UpdateStatus(boutId, roundNumber, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRoundUseCase)(nil).UpdateStatus), boutId, roundNumber, status)
}
